### PR TITLE
Rewrite appstats for google.golang.org/appengine/...

### PR DESCRIPTION
**Pull request by flowlo**
`appstats` now uses the new import paths.

~~I split `appstats.go` into:~~

 1. ~~`appstats.go` with code that refers to `google.golang.org/appengine/...` and `x/net/context`, won't be built with tag `appengine`.~~
 2. ~~`appstats_classic.go` with an implementation using `appengine` and it's `appengine.Context`, will only be built with tag `appengine`.~~
 3. ~~`appstats_common.go` with code shared between them.~~

~~The two implementations are both expose `Context` (which embeds `context.Context` and `appengine.Context` respectively). Those types both implement `appstatsContext`, which I decided not to expose for now, but it helps to get a better picture.~~

~~They both encapsulate `requestStats` and `net/http.Header`.~~

Further minor changes:

 *  `save` will not throw away all stack traces, but only truncate as much as needed, if cracking the maximum buffer size.
 * Introduce `RecordRandom` which is a generalized version of `DefaultShouldRecord` (default semantics were not changed).
 * Slightly change the handler stuff. Now only exposes an `http.Handler`, which can be obtained by converting a function.
 * Throw away `bytesize.go`
 * Move the "internal" handlers (i.e. that save the stats) to `google.golang.org/appengine/...`
 * Buffers are pooled.

~~What's missing: Actually intercepting RPCs. [These portions of code](https://github.com/golang/appengine/blob/d2b1961e346073b2ce8710267c92e4ff4cc0d099/internal/api_common.go#L12-L37) appear to allow registering an override for remote procedure calls. However, the address of `callOverrideKey` is used there to reference those functions which we can not access from `appstats`. @dsymonds could you please give me some hints on how to do that? Or what you would be willing to export?~~

### CODE REVIEW

**Comment by dsymonds** [comment]
Consider changing this to _only_ use `google.golang.org/appengine`. As of 0b86940 it should work comfortably.

**Comment by flowlo** [comment]
@dsymonds Just to be clear: You mean dropping support for the "legacy" ` import  "appengine"` altogether? Thanks for golang/appengine@0b86940! I'll update this PR ASAP.

**Comment by flowlo** [comment]
Updated to use the newly exposed stuff. @mjibson what do you think about dropping `import "appengine"`? I'd be in for it, and this would make `appstats` a lot cleaner.

**Comment by dsymonds** [comment]
Yes, I believe it would be fine to drop any support for `import "appengine"`. I don't think there's any significant remaining use cases that can't switch to the new packages.

**Comment by flowlo** [comment]
I switched to new imports only, with the [combined version still available here](https://github.com/mjibson/appstats/compare/master...flowlo:dual) (for reference).

**Comment by mjibson** [comment]
There are many changes here, not all related. The most important one is the newstyle app engine packages. Could you prepare separate PRs for each logical change instead of one big one? Maybe:

1. new app engine packages
1. style/renaming
1. new http.Handler stuff
1. RecordRandom
1. buffer pool

I'm aware that this is a lot of work, but that's a much better way to review the code than all at once. For example, I'm especially worried about things like misusing the buffer pool, and so I want to see some of those changes without the others.

**Comment by flowlo** [comment]
Yep, I do understand, and TBH I expected you would say that. It's just that I dug deeper and deeper for fun and it turned out I changed a lot. Probably you can relate :) I'll need some time to split this, but will do.

**Pull request closed without merging**
