### PR TITLE
handler: use http.ServeContent for static files

### PR DESCRIPTION
**Pull request by flowlo**
I wrapped the byte slices in `static.go` within `bytes.NewReaders` that implement everything necessary to pass them to `http.ServeContent`. It's the standard way to deal with caching and setting Content-Type for plain files.

### CODE REVIEW

**Comment by mjibson** [comment]
Need a gofmt on static.go

**Comment by mjibson** [comment]
Nevermind on that. Github's isn't displaying the tabs correctly, no fmt needed.

**Comment by flowlo** [comment]
Yep, I ran `gofmt` a few times because I could not stand it, but the files are fine on my end :/

**Comment by mjibson** [comment]
I'm not sure what benefit this patch provides. The current master branch will allow browsers to cache static files themselves (i.e., in the browser). This PR removes that cache, instead forcing each request to also to ask if any of the content was modified, for which the server returns "not modified". So we go from 0 requests if cached to 4 requests (albeit with empty responses). An overall loss based on my understanding.

**Comment by flowlo** [comment]
You can see [from the diff](https://github.com/mjibson/appstats/pull/20/files#diff-8b80bab7c379f59fe83cb4ee2d015ea7L351) that the old expiry time was one hour. So "master branch will allow browsers to cache" is valid only as long as the browser makes at least one request per hour.

Quoting the [docs of `http.ServeContent`](https://golang.org/pkg/net/http/#ServeContent):

> If modtime is not the zero time or Unix epoch, ServeContent includes it in a Last-Modified header in the response. If the request includes an If-Modified-Since header, ServeContent uses modtime to decide whether the content needs to be sent at all.

The `modtime` [with this PR changes to `initTime`](https://github.com/mjibson/appstats/pull/20/files#diff-8b80bab7c379f59fe83cb4ee2d015ea7R80), which is [`time.Now()` at initialization](https://github.com/mjibson/appstats/pull/20/files#diff-8b80bab7c379f59fe83cb4ee2d015ea7R39) (runtime starting up). Assuming the browser sends If-Modified-Since (and decent browsers do that), there will be a Not Modified response as long as the application is not restarted. This is trivial caching, but makes sense to me because when developing locally, you're fine with reloading those resources, and if you access them in a long-running production environment, they'll be requested only exactly once, even when not requesting them for one hour.

> If the caller has set w's ETag header, ServeContent uses it to handle requests using If-Range and If-None-Match.

This would be the best approach, which would definitely put any concern off the table. I propose to compute a SHA256 hash of the static content in `init`, and set the ETag header before calling `http.ServeContent`, which leads to optimal caching our case.

**Comment by mjibson** [comment]
I'm still not convinced that's better. Yes, ServeContent allows empty responses, but it forces an entire request and response (even if it's an empty response) for every page load for every asset. The current hour cache is just fine, and allows the browser to not even make requests for the assets.

**Pull request closed without merging**
