### PR TITLE
Rewrite stack trace parsing for Go 1.5 and clarity

### PR DESCRIPTION
**Pull request by flowlo**

### CODE REVIEW

**Comment by mjibson** [comment]
My stack traces must be different from yours, because I'm always getting odd numbers of lines, and without the "goroutine [...]" line you skip first. See below an example stack trace I get. Using version 1.9.26, linux/amd64.

```
/go/src/github.com/mjibson/appstats/appstats.go:107 (0x557da4)
	override: StackData: string(debug.Stack()),
/go/src/google.golang.org/appengine/internal/api_classic.go:62 (0x618ca1)
	Call: return f(ctx, service, method, in, out)
/go/src/google.golang.org/appengine/user/user.go:63 (0x564bee)
	LoginURLFederated: if err := internal.Call(c, "user", "CreateLoginURL", req, res); err != nil {
/go/src/google.golang.org/appengine/user/user.go:51 (0x564957)
	LoginURL: return LoginURLFederated(c, dest, "")
m.go:17 (0x443813)
	Main: u, err := user.LoginURL(c, "/blah")
/go/src/github.com/mjibson/appstats/appstats.go:300 (0x559e2c)
	handler.ServeHTTP: h.f(ctx, rw, r)
/tmp/appengine/go_appengine/goroot/src/net/http/server.go:1541 (0x4bdf9d)
/tmp/appengine/go_appengine/goroot/src/appengine_internal/api_dev.go:98 (0x43e6e3)
/tmp/appengine/go_appengine/goroot/src/net/http/server.go:1265 (0x4bc831)
/tmp/appengine/go_appengine/goroot/src/net/http/server.go:1703 (0x4bea3a)
/tmp/appengine/go_appengine/goroot/src/net/http/server.go:1204 (0x4bc387)
/tmp/appengine/go_appengine/goroot/src/runtime/asm_amd64.s:2232 (0x43cb01)
```

**Comment by flowlo** [comment]
OK. I got a panic because some index was out of bounds (`cix` I guess) and now it works for me. I'll post a stack trace for comparison ASAP. Just a guess: The trace has an even number of visible lines, but the last line is terminated with `'\n'` making the number of newlines even.

**Comment by flowlo** [comment]
Something else: You are referring to version 1.9.x, which sounds like a SDK or goapp version. That might embed Go <1.5. I use dev_appserver.py which wraps Go 1.5 for me AFAIK and a binary compiled with Go 1.5 on my deployments.

**Comment by flowlo** [comment]
Example stack trace I am getting:

```
goroutine 24 [running]:
google.golang.org/appengine/github.com/coduno/api/controllers.ip(0x7f273ac83390, 0xc82018a4e0, 0xc82018e700)
	/home/lorenz/src/github.com/coduno/api/controllers/ip.go:14 +0x65
net/http.HandlerFunc.ServeHTTP(0xc16738, 0x7f273ac83390, 0xc82018a4e0, 0xc82018e700)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82000a990, 0x7f273ac83390, 0xc82018a4e0, 0xc82018e700)
	/usr/local/go/src/net/http/server.go:1699 +0x17d
google.golang.org/appengine/internal.executeRequestSafely(0xc82018a4e0, 0xc82018e700)
	/home/lorenz/src/google.golang.org/appengine/internal/api.go:151 +0x8d
google.golang.org/appengine/internal.handleHTTP(0x7f273ac83330, 0xc820292840, 0xc82018e700)
	/home/lorenz/src/google.golang.org/appengine/internal/api.go:119 +0x329
net/http.HandlerFunc.ServeHTTP(0xc16c90, 0x7f273ac83330, 0xc820292840, 0xc82018e700)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc820273020, 0x7f273ac83330, 0xc820292840, 0xc82018e700)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820292790)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go
```

Versions:

```
$ gcloud version
Google Cloud SDK 0.9.80

app 2015.09.25
app-engine-java 1.9.26
app-engine-php  
app-engine-python 1.9.26
bq 2.0.18
bq-nix 2.0.18
core 2015.09.25
core-nix 2015.09.03
gcloud 2015.09.25
gsutil 4.15
gsutil-nix 4.14
$ go version
go version go1.5.1 linux/amd64
```

**Comment by mjibson** [comment]
I'm confused. Your stack trace is still generated using `debug.Stack()`, right? My tests don't show the format of that changing in go1.5, so I'm not sure why the existing code is insufficient.

**Comment by flowlo** [comment]
[The old code panics on my stack traces](http://play.golang.org/p/yeof8YfM2f), that's why I changed it in the first place. Now that it works with those traces, I proposed to switch on the Go version at build time to make everyone happy. (BTW, you'll see a stack traces that correlates with what I posted there.)

The stack trace I posted comes from [`panic()`, which calls `systemstack()`](https://golang.org/src/runtime/panic.go), just like [`runtime.Stack`](https://golang.org/pkg/runtime#Stack) (the successor of `runtime/debug.Stack`) [does](https://golang.org/src/runtime/mprof.go?s=15278:15314#L552).

[`runtime/debug.Stack`](https://golang.org/pkg/runtime/debug/#Stack) is deprecated. And with you mentioning it, I just found that [`appstats` callls it](https://github.com/mjibson/appstats/blob/0542d5f0e87ea3a8fa4174322b9532f5d04f9fa8/appstats.go#L107). So it might be worth trying to replace the call to `runtime.Stack`. This may solve our problems.

**Comment by mjibson** [comment]
I'm aware the old code panics on that stack trace. But it's not designed to parse those stack traces, since it doesn't appear to have come from debug.Stack. I'm curious how you even got that stack trace into appstats in the first place.

**Comment by mjibson** [comment]
I am aware that debug.Stack is deprecated and should go away. I searched for a few minutes and was not able to find similar functionality (the actual line of code that was executed) easily available. I'd like to keep that.

**Pull request closed without merging**
